name: AutoSell
main: AutoSell\Main
version: 1.0.0
api: 5.0.0
author: ZyberPE

commands:
  autosell:
    description: Toggle autosell
    usage: /autosell <on|off>
    permission: autosell.use
    aliases: [as]

permissions:
  autosell.use:
    description: Allows use of autosell
    default: op
